pattern_cols: 15 #列
pattern_rows: 15  #行
chessboard_square_size_mm: 11.00

R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1]

camera_name: "hikrobot"
gamma: 0.5
exposure_ms: 10
gain: 10.0
vid_pid: "174F:2435"  #VID（厂商 ID）和PID（产品 ID）
T_gimbal2imubody: [53.866, 0.0, 32.739305]
# 相机内参矩阵，重投影误差: 0.1250px
#camera_matrix: [1307.9830983072609, 0, 642.59515251341747, 0, 1308.7307041812289, 484.13090341524486, 0, 0, 1]
# 相机畸变系数
#distort_coeffs: [-0.098388869239222992, 0.25139873370799032, -2.5998494561825806e-05, -0.00023786989955899325, 0]

# 重投影误差: 0.1167px
camera_matrix: [2420.9112373818243, 0, 713.47158669528005, 0, 2420.4977302172547, 563.48338987330817, 0, 0, 1]
distort_coeffs: [-0.034891364831791644, 0.17109144951744723, 0.00051549167101920209, -0.00015721436272554863, 0]
#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"




# pattern_cols: 10
# pattern_rows: 7
# center_distance_mm: 40

# R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1]

# camera_name: "hikrobot"
# exposure_ms: 3
# gain: 10.0
# vid_pid: "174F:2435"

# #####-----cboard参数-----#####
# quaternion_canid: 0x01
# bullet_speed_canid: 0x110
# send_canid: 0xff
# can_interface: "can0"